# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=26.2
	loader_version=0.19.5

# Mod Properties
	mod_version = 1.0.2
	maven_group = com.smashingmods.alchemistry
	archives_base_name = Alchemistry

# Dependencies
	fabric_version=0.160.0+26.2

rei_version=26.2.821
